### PR TITLE
Update fetch-osm-data.php

### PR DESCRIPTION
**Pull request by raski13**
I have created a working solution. I have tried other solutions with arrays, loops and conditions but I didn't get the desired result.

There is now a new notice: Undefined variable: tag_list in functions.lib.php on line 28

I tried to include the name of the city in the filename on line 86. However, I get the following notice: Notice: Undefined index: addr:city in fetch-osm-data.php on line 86. This is caused by the libraries with no city mentioned. I tried to fix it with a condition but it doesn't work because it doesn't find the search term:
`if (in_array("addr:city", $output)) {
		$city = $transformed_data[$count]["addr:city"]; //includes the city in the filename
		}`
isset() and array_key_exists() don't work as well

### CODE REVIEW

**Comment by iorala** [comment]
Hi @raski13,
Thanks. I updated the .gitignore file, so the output directory doesn't get added to the git index anymore. 

Also I added JSON_PRETTY_PRINT to json_encode. This makes the output much more readable. 

I wouldn't include the cities in the filenames. Instead I'd suggest to only output one  file per canton, plus one file containing the library counts for all cantons. Using the testing data for TI, this should result in two files: libs/library_count.txt  and libs/libraries_TI.txt.

Can we try to fix this on your branch before merging? Do you need help?

**Comment by raski13** [comment]
Hi @iorala 
I just forgot to add the library_count.txt. Same goes for JSON_PRETTY_PRINT. I added it once, changed my code and forgot to add it again.

I look up your suggestion to only output one file per canton tomorrow evening. I don't have time before.

I'm working on my branch.

**Comment by iorala** [comment]
Thanks for the update. I did some smaller bugfixes in your branch:
- the slashes in the URLs were being escaped: see issue #23 
  - I put in `JSON_UNESCAPED_SLASHES` to solve this
- Our testing data didn't contain any Unicode characters
  - I added some umlauts, ligatures and other weird stuff including emojis to the last library (USI in Lugano) 
  -  I ran a test against it and discovered, that this was being escaped as well
  - To fix this behaviour I added `JSON_UNESCAPED_UNICODE`
- Due to the `json_encode()` options our script now requires at least PHP 5.4. I put this into the README.md in the master branch see commit https://github.com/iorala/osm-libch/commit/4468ca7bb80c7e570c18d140e6fc608c1c1a3b87

**Comment by iorala** [comment]
Looks good. I'll merge it.

**Pull request merged**
